robotslist.php
UptimeRobot is a service that pings your website and alerts you when it's down. (https://uptimerobot.com/)
=> Add UptimeRobot to the bot list

includes/classes/statistics.class.php, includes/functions/country-codes.php
The different contexts allow different translation for some languages
=> Add missing Gettext to "Unknown" items with different contexts

includes/log/top-referring.php
This missing </div> is causing the log items to wrap each others
=> Add missing closing </div> tag

includes/log/top-referring.php
This string shows the links from a specific site
=> Correct string meaning

includes/templates/plugins.php
Also change Deactivate to Inactive, as it's the actual opposite of Active status
=> Add missing gettext functions

widget.php
fix somethings wrong
there are some values which are not set (Removed!)
and .......
=> fix somethings wrong

ajax.php, includes/log/page-statistics.php
- Remove html from translation strings
- Complete sentence with variable to understand context
=> Improve strings i18n

ajax.php, dashboard.php, includes/log/log.php, includes/log/searched-phrases.php, includes/log/widgets/searched.phrases.php, wp-statistics.php
Added Top Searched Phrases & Widget
=> Added Top Searched Phrases & Widget

includes/log/widgets/countries.php
=> optimized query

readme.txt, wp-statistics.php
Added docs
Modified Tags
Modified 'Tested up to'
Removed some unused variables
=> Optimization

includes/settings/tabs/wps-general.php, wp-statistics.php
Removed wp_statistics_language
=> removed wp_statistics_language

includes/classes/class-wp-statistics.php, wp-statistics.php, wps-install.php, wps-uninstall.php
=> moved to class

includes/classes/class-wp-statistics-bootstrap.php, includes/classes/class-wp-statistics-geo-ip-hits.php, includes/classes/class-wp-statistics-hits.php, includes/classes/class-wp-statistics-install.php, includes/classes/class-wp-statistics-schedule.php, includes/classes/class-wp-statistics.php, includes/classes/important.txt, includes/log/page-statistics.php, includes/log/top-visitors.php, includes/log/widgets/quickstats.php, includes/optimization/wps-optimization.php, includes/settings/tabs/wps-exclusions.php, includes/settings/wps-settings.php, wp-statistics.php
better performance of loading files
=> better performance of loading files

includes/settings/wps-settings.php
=> fix includes

readme.txt
=> modify tags

includes/classes/class-wp-statistics.php
=> dynamic version

includes/classes/class-wp-statistics.php
=> add load_plugin_textdomain

assets/css/admin.css, includes/classes/class-wp-statistics-bootstrap.php, includes/classes/class-wp-statistics-dashboard.php
=> fix admin.css loading

includes/log/widgets/referring.php
fix referrers urls
support request:
https://wordpress.org/support/topic/ref-url/
=> fix referrers urls

includes/classes/class-wp-statistics-bootstrap.php, includes/classes/class-wp-statistics-install.php, includes/classes/class-wp-statistics-schedule.php, includes/classes/class-wp-statistics-uninstall.php, includes/classes/class-wp-statistics-updates.php, includes/classes/class-wp-statistics.php, wp-statistics.php
=> fix for download_url function

includes/classes/class-wp-statistics-admin.php, includes/classes/class-wp-statistics-frontend.php, includes/classes/class-wp-statistics-install.php, includes/classes/class-wp-statistics.php, wp-statistics.php
=> move to classes

includes/classes/class-wp-statistics-hits.php, includes/classes/class-wp-statistics.php
=> converted to method

includes/classes/class-wp-statistics-geo-ip-hits.php, includes/classes/class-wp-statistics-hits.php, includes/classes/class-wp-statistics.php
=> fix for hits class

includes/classes/class-wp-statistics-admin.php, includes/classes/class-wp-statistics-bootstrap.php, includes/classes/class-wp-statistics-frontend.php, includes/classes/class-wp-statistics-hits.php, includes/classes/class-wp-statistics.php
=> move to correct class

includes/classes/class-wp-statistics-frontend.php, includes/classes/class-wp-statistics.php, includes/functions/functions.php
=> Fix widgets

includes/classes/class-wp-statistics-admin.php
=> improve admin

includes/classes/class-wp-statistics-admin.php
=> removed slow constant

includes/classes/class-wp-statistics-admin-pages.php, includes/classes/class-wp-statistics-admin.php
=> separate admin pages

includes/classes/class-wp-statistics.php
=> documentation

includes/optimization/tabs/wps-optimization-export.php, includes/optimization/tabs/wps-optimization-purging.php, includes/settings/tabs/wps-access-level.php, includes/settings/tabs/wps-notifications.php
=> fix directions

includes/classes/class-wp-statistics-hits.php
=> fix detect ajax request

assets/css/log.css, includes/classes/class-wp-statistics-admin-pages.php, includes/classes/class-wp-statistics.php, includes/log/widgets/referring.php
fix refferer widget db and display
=> fix refferer widget db and display

includes/classes/class-wp-statistics-ajax.php, includes/classes/class-wp-statistics-hits.php, includes/log/widgets/pages.php, includes/log/widgets/referring.php
=> fix load of ajax pages

includes/log/top-countries.php
=> fix top countries process

includes/log/top-countries.php
=> fix prefix

includes/log/widgets/countries.php
=> optimize countries widget

includes/classes/class-wp-statistics-admin.php, includes/classes/class-wp-statistics-frontend.php, includes/classes/class-wp-statistics.php
=>  fix php compatibility check

includes/classes/class-wp-statistics-widget.php
This will merge with already existent similar strings.
- Average Posts -> Post Average
- Average Comments -> Comment Average
- Average Users -> User Average
=> Corrects strings text

includes/classes/class-wp-statistics-updates.php, includes/settings/tabs/wps-externals.php
=> rename piwik to matomo

includes/admin/pages/class-wp-statistics-admin-page-settings.php, includes/admin/templates/settings/general.php, includes/class-wp-statistics-option.php, includes/class-wp-statistics-visitor.php, src/Service/Admin/Referrals/ReferralsManager.php, src/Service/Admin/SiteHealthInfo.php, src/Service/Analytics/Referrals/Referrals.php, src/Service/Analytics/Referrals/ReferralsParser.php, src/Service/Analytics/VisitorProfile.php, src/Utils/Url.php
Added option to choose between **First-Touch**, or **Last-Touch** attribution models for referrals.
-   [ ] Enhancement - Improvement to existing functionality
=> Release v14.11 last touch model

includes/admin/templates/optimization/updates.php, readme.txt, src/Async/BackgroundProcessFactory.php, src/Async/CalculatePostWordsCount.php, src/Async/IncompleteGeoIpUpdater.php, src/Async/SourceChannelUpdater.php, src/Models/VisitorsModel.php, src/Service/Admin/Referrals/ReferralsPage.php, src/Utils/Query.php
Fix memory exhaustion issue during running background process
-   [x] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality
=> Release v14.11 fix bp memory issue

src/Models/VisitorsModel.php
Fix referrers landing page issue
-   [ ] Enhancement - Improvement to existing functionality
=> fix: referrers landing page issue

readme.txt, src/Service/Admin/SiteHealthInfo.php, src/Service/Geolocation/GeoServiceProviderInterface.php, src/Service/Geolocation/Provider/DbIpProvider.php, src/Service/Geolocation/Provider/MaxmindGeoIPProvider.php
New method to check the Geolocation validity and also called in site info.
-   [ …
=> feat: add method geolocation validation

readme.txt, src/Service/Admin/Posts/PostsManager.php
Removed widgets for non-published post types.
- My code follows the style guidelines of this project. …
=> Fix widgets issue unpublished posts

includes/admin/templates/pages/devices/models.php, readme.txt, src/Service/Admin/Devices/DevicesDataProvider.php
ixed the device model percentage issue under the Devices > Device Models tab and reformatted the percentage to one decimal place.
- …
=> Fix device model percentage issue

readme.txt, src/Service/Admin/Posts/HitColumnHandler.php
Removed the `views` custom column for non-published post types.
-   [ ] …
=> Fix views column issue unpublished posts

readme.txt, src/Service/Admin/LicenseManagement/LicenseManagementManager.php, src/Service/Admin/PrivacyAudit/PrivacyAuditManager.php
Updated the visibility of the `Add-ons` and `Privacy Audit` menu items to depend on the `Minimum Role to Manage Settings` configuration on settings page.
-   [ ] Dev - …
=> Improve addons and privacy audit show condition

readme.txt, src/Service/Admin/Posts/PostsManager.php
The sortable `views` column functionality has been fixed and works correctly for all post types including the `views` column.
-   [ …
=> Fix views sortable issue

readme.txt, src/Components/AssetNameObfuscator.php
Resolved PHP deprecation issue when disabling the "Bypass Ad Blockers" setting.
- …
=> Fix php deprecated issue

.github/workflows/ai_code_review.yml
This update adds the `ai_code_review.yml` file to automate code reviews using AI, ensuring security best practices and smooth integration.
-   [x] Dev - Development …
=> Implement ai code review

includes/class-wp-statistics-exclusion.php, readme.txt
Resolved issue with undefined array key `robot_threshold` in the exclusion_robot_threshold method to ensure proper handling of array keys and prevent runtime errors.
-   [ …
=> Fix undefined array key

includes/class-wp-statistics-admin-bar.php, readme.txt, src/Abstracts/BaseModel.php, src/Models/HistoricalModel.php, src/Models/ViewsModel.php, src/Models/VisitorsModel.php, src/Service/Admin/Posts/HitColumnHandler.php, src/Utils/Url.php
Added historical codes to the model and updated its functionality in the `ViewModel` to calculate historical data if needed. It should work as before.
-   [ ] Dev - …
=> Improve queries to consider historical data

includes/class-wp-statistics-frontend.php, readme.txt
Resolved the homepage view issue. …
=> Fix homepage views issue

readme.txt, src/Service/Admin/SiteHealthInfo.php
Added the `Location Detection Method` feature to Site Health.
-   [ ] Performance …
=> Add site health location detection

includes/class-wp-statistics-frontend.php, src/Components/RemoteRequest.php, src/Service/Analytics/AnalyticsController.php, src/Service/Debugger/Provider/TrackerProvider.php, views/pages/tracker-debugger/tracker-debugger.php
Add response check to the tracker debugger …
=> Add tracker response check

src/Models/HistoricalModel.php, src/Service/Admin/Metabox/Metaboxes/TrafficOverview.php
Resolved historical data calculation for visitors
-   [ ] Enhancement - …
=> Fix historical data calculation

includes/class-wp-statistics-purge.php, readme.txt
Fixed recording inaccurate historical data while purging "visit" table.
-   [ ] …
=> Release 14.12 fix purge data issue

src/Models/VisitorsModel.php, src/Service/Admin/Metabox/MetaboxDataProvider.php, views/metabox/traffic-overview.php, views/metabox/traffic-summary.php
Show summary widget data based on visitor hits …
=> Show summary widget data based on hits

src/Models/VisitorsModel.php, src/Service/Admin/CategoryAnalytics/CategoryAnalyticsDataProvider.php, src/Service/Admin/ContentAnalytics/ContentAnalyticsDataProvider.php, src/Service/Admin/Geographic/GeographicDataProvider.php, src/Service/Admin/Metabox/MetaboxDataProvider.php, src/Service/Admin/Referrals/ReferralsDataProvider.php, src/Service/Charts/DataProvider/SocialMediaChartDataProvider.php, src/Service/Charts/DataProvider/SourceCategoryChartDataProvider.php
=> Release 14.12 referrers improvements

src/Components/RemoteRequest.php, src/Service/Debugger/Provider/TrackerProvider.php, views/pages/tracker-debugger/tracker-debugger.php
Resolved the tracker response check issue on the Tracker Debugger with Cloudflare Challenge. …
=> Fix tracker issue with cloudflare

readme.txt, src/Service/Debugger/Provider/TrackerProvider.php
Resolved the tracker file detection issue in the tracker debugger for sites in subfolders.
-   [ ] Tweak - A minor adjustment to the …
=> Resolved tracker file detection issue for sites in subfolders

includes/admin/templates/layout/filters/referrer-filter.php, readme.txt
Resolved Filters option incorrectly activating when changing the date filter in Referrals.
-   [ ] Tweak - A minor adjustment to the …
=> Resolved filters activating on date change

includes/class-wp-statistics-timezone.php, readme.txt
Display Now instead of 0 minutes ago in Tracker Debugger. …
=> Improve date format in tracker debugger

readme.txt, src/Async/BackgroundProcessFactory.php
Set the memory limit to unlimited when starting the source channel background process
-   [ ] Tweak - A minor adjustment to the …
=> Release 14.12.x fix memory limit issue

includes/class-wp-statistics.php, src/Async/DataMigrationProcess.php, src/Async/SchemaMigrationProcess.php, src/Async/TableOperationProcess.php, src/Service/Admin/Database/AbstractDatabaseOperation.php, src/Service/Admin/Database/DatabaseFactory.php, src/Service/Admin/Database/DatabaseManager.php, src/Service/Admin/Database/Managers/MigrationHandler.php, src/Service/Admin/Database/Managers/TableHandler.php, src/Service/Admin/Database/Managers/TransactionHandler.php, src/Service/Admin/Database/Migrations/AbstractMigrationOperation.php, src/Service/Admin/Database/Migrations/DataMigration.php, src/Service/Admin/Database/Migrations/SchemaMigration.php, src/Service/Admin/Database/Operations/AbstractTableOperation.php, src/Service/Admin/Database/Operations/Create.php, src/Service/Admin/Database/Operations/Drop.php, src/Service/Admin/Database/Operations/Insert.php, src/Service/Admin/Database/Operations/Inspect.php, src/Service/Admin/Database/Operations/Update.php, src/Service/Admin/Database/Schema/Manager.php
Added a database manager with all required operations and migrations based on versions …
=> Feat: base db manager

includes/class-wp-statistics-ip.php, readme.txt
Updated the hash IP algorithm.
- …
=> refactor: updated hash ip algorithm

views/pages/tracker-debugger/tracker-debugger.php
---
- https://app.asana.com/0/0/1209277940841410
=> fix: Fix show error on Tracker.js

includes/class-wp-statistics-frontend.php, readme.txt, src/Components/Assets.php
Added support for `defer` and `async` loading strategies for the Tracker JS script to improve script execution efficiency.
Updated core assets script to accept and handle loading strategies dynamically.
Introduced a new filter: `wp_statistics_{$handle}_loading_strategy,` allowing developers to modify the script loading strategy as needed.
- My code follows the style guidelines of this …
=> feat: Added support for loading strategies for the tracker script

CHANGELOG.md, includes/admin/templates/header.php, includes/class-wp-statistics-user-online.php, src/Service/Admin/Metabox/Metaboxes/CurrentlyOnline.php, src/Service/Admin/VisitorInsights/Views/TabsView.php, views/metabox/traffic-overview.php, views/metabox/traffic-summary.php
---
- https://app.asana.com/0/0/1209087885429956
=> Release 14.12.x improve monitor online visitors setting

includes/class-wp-statistics-referred.php, readme.txt
Resolved missing sites/domains while getting the list of the referring.
-   [ ] …
=> fix: missing referring domains

CHANGELOG.md, src/Service/Admin/Posts/HitColumnHandler.php
---
- https://app.asana.com/0/0/1208929685991892
=> Release 14.12.x fix mini chart date issue

CHANGELOG.md, src/Models/OnlineModel.php
Resolved missing online visitor data on the Online Visitor List.
-   [ ] …
=> Fixed online visitor issue

includes/libraries/wp-background-processing/wp-background-process.php, src/Async/DataMigrationProcess.php, src/Service/Admin/Database/Managers/MigrationHandler.php, src/Service/Admin/Database/Migrations/AbstractMigrationOperation.php, src/Service/Admin/Database/Operations/AbstractTableOperation.php, src/Service/Admin/Database/Operations/MultiStepOps/VisitorSearchInsert.php, src/Service/Admin/Database/Operations/Update.php
Implement the retry button for migrations.
-   [ ] Enhancement - Improvement to …
=> feat: implement retry button for migrations

CHANGELOG.md, src/Service/Admin/Metabox/MetaboxDataProvider.php
Resolve statistical discrepancies in widgets. …
=> Release 14.12.x fix statistical discrepancy in widgets

CHANGELOG.md, includes/class-wp-statistics-pages.php, includes/template-functions.php, src/Models/AuthorsModel.php, src/Models/OnlineModel.php, src/Models/PostsModel.php, src/Models/TaxonomyModel.php, src/Models/ViewsModel.php, src/Models/VisitorsModel.php, src/Service/Charts/DataProvider/MapChartDataProvider.php
Improved query performance.
-   [x] Performance - Address performance issues
- …
=> pref: improve query performance

src/Async/BackgroundProcessMonitor.php, src/Async/DataMigrationProcess.php, src/Service/Database/Managers/MigrationHandler.php, src/Service/Database/Migrations/DataMigration.php, src/Service/Database/Operations/MultiStepOps/VisitorSearchInsert.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
added functionality of progress of the background process.
-   [ ] Enhancement - …
=> feat: added background process progress

src/Models/AuthorsModel.php, src/Utils/Query.php
=> pref: optimize database query.

CHANGELOG.md, src/Service/Admin/Metabox/MetaboxDataProvider.php
Reduced the displayed record count in the Top Countries widget to 5.
-   [ ] …
=> fix: reduce the displayed record count in the Top Countries widget to 5.

CHANGELOG.md, src/Service/Analytics/Referrals/ReferralsParser.php
Fixed referrals source name issue …
=> Release 14.12.x fix referrals source issue

includes/class-wp-statistics-helper.php, includes/class-wp-statistics-install.php, src/Service/Admin/AjaxOptionUpdater.php, src/Service/Admin/Notification/NotificationConditionTags.php
Added new notification conditions. …
=> fix: add new notification conditions

src/Service/Admin/Notification/NotificationManager.php
Updated cron schedule for notifications to run daily. …
=> fix: update cron schedule for notifications to run daily

src/Decorators/NotificationDecorator.php
Corrected notifications icon and description fields. …
=> fix: correct notifications icon and description fields

CHANGELOG.md, src/Service/Admin/AnonymizedUsageData/AnonymizedUsageDataProvider.php
Removed table prefix from shared data. …
=> fix: removed table prefix from shared data.

CHANGELOG.md, includes/admin/pages/class-wp-statistics-admin-page-settings.php, includes/admin/templates/settings/exclusions.php, includes/class-wp-statistics-exclusion.php
Removed the `Host Exclusions` on settings page. …
=> remove the `Host Exclusions` on settings page

CHANGELOG.md, src/Service/Admin/Referrals/ReferralsPage.php
=> Release 14.13.x fix filters url issue

views/components/headers/post-type.php
Added link post type in single post header to page insights.
-   [ ] …
=> add link post type in single post header to page insights

CHANGELOG.md, src/Service/Admin/FilterHandler/FilterManager.php
Fix filters-related PHP warnings. …
=> Release 14.13.x fix filters issue

CHANGELOG.md, includes/class-wp-statistics-schedule.php, includes/class-wp-statistics.php, src/Service/Database/Managers/MigrationHandler.php
Fixed early translation loading warning. …
=> fix: early translation loading warning.

CHANGELOG.md, src/Models/PostsModel.php
=> fix: get recent comments by comment date

CHANGELOG.md, src/BackgroundProcess/AjaxBackgroundProcess/AjaxBackgroundProcessFactory.php, src/BackgroundProcess/AjaxBackgroundProcess/AjaxBackgroundProcessManager.php
Restricted migration process to plugin admin pages only
-   [x] Performance - …
=> refactor: restrict migration process to plugin admin pages only

src/Abstracts/BasePage.php, src/Abstracts/BaseView.php, src/Service/Admin/AuthorAnalytics/Views/AuthorsView.php, src/Service/Admin/AuthorAnalytics/Views/PerformanceView.php, src/Service/Admin/AuthorAnalytics/Views/SingleAuthorView.php, src/Service/Admin/CategoryAnalytics/Views/SingleView.php, src/Service/Admin/CategoryAnalytics/Views/TabsView.php, src/Service/Admin/ContentAnalytics/Views/SingleView.php, src/Service/Admin/ContentAnalytics/Views/TabsView.php, src/Service/Admin/Devices/Views/TabsView.php, src/Service/Admin/Exclusions/ExclusionsPage.php, src/Service/Admin/Geographic/Views/TabsView.php, src/Service/Admin/LicenseManagement/Views/TabsView.php, src/Service/Admin/Overview/OverviewPage.php, src/Service/Admin/PageInsights/Views/TabsView.php, src/Service/Admin/PrivacyAudit/PrivacyAuditPage.php, src/Service/Admin/TrackerDebugger/TrackerDebuggerPage.php, src/Service/Admin/VisitorInsights/Views/TabsView.php
Improve error handling in views …
=> Release 14.13.x improve error handling

CHANGELOG.md, includes/class-wp-statistics-helper.php, src/Service/HooksManager.php, tests/unit/Test_NumberFormatter.php
Removed `Get Premium` action link if license is available.
-   [ ] Performance …
=> fix: removed `Get Premium` action link if license is available.

includes/admin/class-wp-statistics-admin-ajax.php, includes/admin/pages/class-wp-statistics-admin-page-settings.php
Fix word count notice issue 
- …
=> fix: word count notice issue

views/components/modals/introduce-premium/step-details.php
---
- https://app.asana.com/0/0/1210283303068673
=> fix : Fix upgrade to premium link

views/components/tables/referrers.php, views/components/tables/top-referrers.php, views/metabox/top-referring.php
---
- https://app.asana.com/0/0/1210286556375780
=> pref : Update referral links

src/Service/Admin/ContentAnalytics/Views/SingleResourceView.php, views/components/headers/single-resource.php
Fix single resource encoded URI issue …
=> fix: single resource encoded uri issue

CHANGELOG.md, src/Models/ViewsModel.php, src/Service/Admin/VisitorInsights/Views/TabsView.php, src/Service/Admin/VisitorInsights/VisitorInsightsDataProvider.php, views/components/tables/views.php, views/pages/visitor-insights/views.php
=> Release 14.14.x update views report

CHANGELOG.md, views/components/visitor-information.php
---
- https://app.asana.com/0/0/1210463770653969
=> feat : Add Country Name to Visitor Info Flag Tooltip

includes/class-wp-statistics-admin-bar.php
---
- https://app.asana.com/0/0/1210434483840762
=> fix : Fix missing alt text

CHANGELOG.md, src/Service/Integrations/IntegrationsManager.php, src/Service/Integrations/Plugins/AbstractIntegration.php, src/Service/Integrations/Plugins/RealCookieBanner.php, src/Service/Integrations/Plugins/WpConsentApi.php
=> fix: unset consent integration option upon deactivation

CHANGELOG.md, src/Service/Admin/HelpCenter/HelpCenterManager.php
Added unread notification badge to Help Center menu. …
=> feat: add unread notification badge to Help Center menu.

CHANGELOG.md, includes/class-wp-statistics-install.php, includes/class-wp-statistics-uninstall.php, src/Service/CronEventManager.php
Combined notification and marketing campaign cron jobs into a single daily scheduled event to optimize scheduling.
-   [ ] Tweak - …
=> refactor: consolidate daily cron events into a single scheduled event.

src/Models/VisitorsModel.php
=> feat: add exit rate column

CHANGELOG.md, src/Traits/TransientCacheTrait.php
Transient cache duration issue …
=> Release 14.15.x fix cache multiply issue

src/Service/Admin/LicenseManagement/Plugin/PluginActions.php
=> fix: minor issues

src/Service/Database/Migrations/Queue/QueueFactory.php
Fix issue with queue migration on fresh installations. …
=> fix: fresh condition issue in queue migration

CHANGELOG.md, src/Service/Database/DatabaseHelper.php, src/Service/Database/Migrations/Ajax/AjaxManager.php, src/Service/Database/Migrations/Queue/QueueManager.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Fixed migration redirect issue: the redirect URL is now compatible with sites in subfolders.
-   [ ] Tweak - A minor adjustment to …
=> Fix migration redirect url

CHANGELOG.md, src/Service/Database/Migrations/Queue/QueueFactory.php, src/Service/Database/Migrations/Queue/QueueManager.php
Fix logic: only display the queue migration notice when a migration is required.
-   [ ] Tweak - A minor adjustment to the …
=> Fix false queue migration notice

includes/class-wp-statistics-install.php, includes/class-wp-statistics.php
Revert the change that removed running the legacy install class to prevent any unforeseen issues with add-ons
-   [ ] Performance …
=> Release 14.15.x revert required install class

CHANGELOG.md, includes/class-wp-statistics-cli.php
Reverts wp-statistics/wp-statistics#979
=> Revert "fix(cli): avoid fatal error when running `wp statistics reinitialize`"

CHANGELOG.md, includes/class-wp-statistics-cli.php
Renamed WP-CLI command `wp statistics reinitialize` to `wp statistics create_tables` for clarity.
-   [ ] Tweak - A minor …
=> feat(cli): rename reinitialize command to create_tables

includes/class-wp-statistics-helper.php
...
-   [x] Dev - Development related task
-   [ ] Enhancement - …
=> feat: add new pattern to detect oracle injections

CHANGELOG.md, src/Abstracts/BasePage.php, src/Abstracts/MultiViewPage.php
=> feat: add date range validation to pages

includes/admin/templates/settings/add-ons/advanced-reporting.php, includes/admin/templates/settings/notifications.php, includes/class-wp-statistics-helper.php
Fix schedule issues
-   [x] Dev - Development related task
-   [ ] …
=> feat: add method for displaying report schedules
