- includes/log/all-browsers.php
- includes/log/authors.php
- includes/log/categories.php
- includes/log/exclusions.php
- includes/log/hit-statistics.php
- includes/log/last-search.php
- includes/log/last-visitor.php
- includes/log/online.php
- includes/log/page-statistics.php
- includes/log/search-statistics.php
- includes/log/tags.php
- includes/log/top-countries.php
- includes/log/top-pages.php
- includes/log/top-referring.php
- includes/log/top-visitors.php
Solves issue https://github.com/wp-statistics/wp-statistics/issues/8
As explained in the issue description, this changes followed the same code pattern of WordPress dashboard panels rendered code, adding the following:
- screen reader text
- toggle indicator arrow
- key navigation
- UI and Translation strings consistent with core
> Show Toggle indicator arrows and titles for Statistics panels

- dashboard.php
- editor.php
- includes/log/log.php
Adds:
- screen-reader-text to metabox Reload and More button
- title attribute to metabox Reload and More button
Adding the titles keeps it consistent with the previously existent Toggle buttons, despite WP core doesn't use any title attributes in metaboxes buttons.
If you choose not tu use `title` button attribute, it should also be deleted from the several metaboxes code `<button class="handlediv" type="button" title="<?php printf( __( 'Toggle panel: %s', 'wp_statistics' ), $paneltitle ); ?>">` added in the commit https://github.com/wp-statistics/wp-statistics/commit/23724efb571c75e21d9704558407bf93439da94b
> Add title and screen reader text to metabox More and Reload buttons

- dashboard.php
- editor.php
- includes/log/all-browsers.php
- includes/log/authors.php
- includes/log/categories.php
- includes/log/exclusions.php
- includes/log/hit-statistics.php
- includes/log/last-search.php
- includes/log/last-visitor.php
- includes/log/log.php
- includes/log/online.php
- includes/log/page-statistics.php
- includes/log/search-statistics.php
- includes/log/tags.php
- includes/log/top-countries.php
- includes/log/top-pages.php
- includes/log/top-referring.php
- includes/log/top-visitors.php
- readme.txt
Remove redundant and unnecessary `title` attributes from widget metabox buttons.
Add `aria-expanded="true"`
This makes the metaboxes consistent with [WP core metaboxes code](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/template.php#L1050)
> Widget metabox buttons consistent with WP core

- assets/css/admin.css
- assets/css/log.css
This fixes the issue mentioned [here](https://github.com/wp-statistics/wp-statistics/commit/6918fda7704838accedacf18043358e4272b0b25#commitcomment-24739044)
> Move metabox buttons CSS to log.css

- includes/classes/class-wp-statistics-hits.php
check cronjon request and don't log as a hit
related support ticket:
https://wordpress.org/support/topic/cron-jobs-counting-as-visits/
> check cronjon request

- assets/css/admin.css
fix adminbar icon issue
related support request:
https://wordpress.org/support/topic/why-is-the-icon-in-the-admin-bar-hidden/
> fix adminbar icon issue

- includes/classes/class-wp-statistics.php
In some situations REMOTE_ADDR might not point to the visitors address but the upstream proxy server. This leads to WP-Statistics only recording the same (server) IP over and over again. This change checks for the presence of typical headers proxys use to forward the originators IP and - if present - use these instead.
Note: Since these headers are not standardized this might still not work - making this section configurable would probably be a better idea in the long run
> Basic support for reverse proxys/CDNs/Docker/etc

- assets/css/frontend.css
The opt out bar is - depending on the theme used - unreadable due to other elements floating in front. z-index should fix this.
Additionally the text is hard to read if other text is displayed behind due to the high transparency, lowered here.
Lastly a nice bar to clearly separate the overlayed opt-out-bar from the rest of the content
> Opt-Out: Improve visibility

- includes/classes/class-wp-statistics.php
The changes in https://github.com/wp-statistics/wp-statistics/pull/122 where mostly unnecessary since a similar code is already present.  This should revert my last change and fix the original code. Sorry for the inconvenience, I better get some sleep before fixing stuff...
> Revert proxy changes and repair original code

- includes/classes/class-wp-statistics.php
If the user hasn't explicitly stated otherwise but sends the "Do-not-track" header treat him as if he opted out.
https://en.wikipedia.org/wiki/Do_Not_Track
> Support for DNT-Header

- assets/css/frontend.css
* The div will be added into the .content div. Some themes have a padding/margin for that div. Thus, I added `left: 0; right: 0;`
* Transparent background makes the message hard to read in case there is some other text underneath it.
> Improved styling of opt-out message

- includes/template-functions.php
Hi,
I had a use case where I wanted to get the top pages of a particular custom post type on my site. This solution seems to be a quick way to update the `wp_statistics_get_top_pages()` function to accept a slug(s) of a custom post type(s) to filter results by. 
Example usages: 
`wp_statistics_get_top_pages(null, null, null, 'resource')`
`wp_statistics_get_top_pages(null, null, null, array('resource', 'series'))`
Thanks,
Henry
> Ability to filter wp_statistics_get_top_pages() by post type

- includes/admin/class-wp-statistics-admin-taxonomy.php
Hi,
I was about to report the bug regarding the function for the custom taxonomy columns not returning any value, when I saw this already got addressed in 0f242fde401d91ee692a53385b349b58c394c03c on the development branch.
Still, I have this little suggestion for improvement, as filter functions must not echo anything.
Do you have a rough estimate, when the bug fix will be available as part of an update? A user of my plugin gets fatal errors on some taxonomy admin pages because of it.
Thanks,
Andreas
> Small tweak for taxonomy custom column filter function

- CHANGELOG.md
- includes/admin/class-wp-statistics-admin-post.php
- includes/admin/class-wp-statistics-admin-taxonomy.php
- languages/wp-statistics.pot
- readme.txt
1. Consider historical results in hits order query when sorted by views. 
2. Skip historical calculation if `count_display` option is not set to `total`. 
3. Skip hits queries execution if `count_display` is disabled. 
4. Small refactors. 
> Related to https://github.com/wp-statistics/wp-statistics/pull/512 (point 4) 
> [Asana Card](https://app.asana.com/0/1198503983922005/1207972027852584/f)
> Improve post hits when sorted by views

- includes/class-wp-statistics-helper.php
- readme.txt
This PR fixes the `urlToDir` function to correctly resolve plugin paths in Bedrock environments. It uses `WP_PLUGIN_DIR` and `basename()` to eliminate redundant path segments, ensuring the correct directory path is returned without duplication of /app.
-   [x] Fix - Fixes an existing …
> fix: Fix urlToDir function for Bedrock

- readme.txt
- src/Service/Admin/LicenseManagement/LicenseManagementManager.php
This update fixes the early translation loading issue by moving the `get_plugin_data` function call to the `init` hook.
-   [ ] …
> Fix early translation loading issue

- CHANGELOG.md
- src/Utils/Query.php
Fixed database errors across the application caused by using %i for identifiers in WordPress queries. This issue affected multiple areas, including Page Insight, Visitor Insight, and the Update User functionality.
- …
> fix: DB errors due to %i usage in WP queries

- src/Service/Admin/SiteHealthInfo.php
- src/Service/Admin/TrackerUsageData/TrackerUsageDataProvider.php
Add addons settings fields to usage data tracker …
> fix: add addons settings fields to usage data tracker

- CHANGELOG.md
- src/Service/Admin/Metabox/MetaboxDataProvider.php
Reduced the displayed record count in the Top Referring widget to 5.
-   [ ] …
> fix: reduce the displayed record count in the Top Referring widget to 5

- src/Service/Admin/Notification/NotificationConditionTags.php
Added `wp-statistics-` prefix to tags. …
> fix: add `wp-statistics-` prefix to tags

- CHANGELOG.md
- src/Service/Debugger/Provider/ErrorsDetectorProvider.php
Introduced the `wp_statistics_disable_tracker_debugger_logs` filter to allow disabling tracker debugger error logs.
Useful for reducing noise in logs and improving clarity in production environments.
-   [ ] Update - …
> Add filter to disable tracker debugger error logging

- CHANGELOG.md
- includes/class-wp-statistics-country.php
- includes/class-wp-statistics-timezone.php
Fixed a warning by validating geographic location codes are strings or integers before use.
-   [ ] Tweak - A minor adjustment to …
> fix: validate geographic location codes to prevent warnings

- CHANGELOG.md
- includes/class-wp-statistics-option.php
- src/Service/Debugger/Provider/ErrorsDetectorProvider.php
The code that limits the number of errors has been updated: instead of deleting only the first entry, it now removes the oldest entries (from the beginning of the list) as needed to cap the option group at 10 items.
Additionally, an error-message length limiter was added. Messages longer than 1000 characters are truncated to 1000. This limit is configurable via the `wp_statistics_tracker_debugger_log_message_max_length` filter.
- Following the above guidelines will result in quick merges and clear …
> Prevent tracker_js_errors option bloat

- CHANGELOG.md
- src/Service/Database/Managers/TableHandler.php
Prevents the “Queue Migration” Done notice from appearing right after an update and shows it only once the migration has actually completed.
-   [ ] Dev - Development …
> fix: incorrect queue migration completion notice after update
